### ISSUE TITLE
Hello 2 question :)

### ISSUE THREAD

**Issue by Spyrson** [KevinLage/YouTube-Livestream-Botter#10]
root@ubuntu-s-4vcpu-8gb-nyc3-01:~/nowy/YouTube-Livestream-Botter# python YouTube\ Livestream\ Botter.py kdtkyYid7YA 1000
  File "YouTube Livestream Botter.py", line 14
SyntaxError: Non-ASCII character '\xe2' in file YouTube Livestream Botter.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I have this error when try open this in ubuntu on windows work good ;/

root@ubuntu-s-4vcpu-8gb-nyc3-01:~/nowy/YouTube-Livestream-Botter# python YouTube\ Livestream\ Botter.py
  File "YouTube Livestream Botter.py", line 14
SyntaxError: Non-ASCII character '\xe2' in file YouTube Livestream Botter.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by KevinLage** [comment]
hm which ubuntu version?

**Comment by Spyrson** [comment]
Ubuntu 18.04.3 (LTS) x64

**Comment by KevinLage** [comment]
I am using Ubuntu 19.10 and everything works
