### ISSUE TITLE
How many viewers?

### ISSUE THREAD

**Issue by HeartWell** [KevinLage/YouTube-Livestream-Botter#101]
How many viewers do you get? The maximum of 200 then falls to 50 and again 200 and so constantly, threads 1000.

**Comment by KevinLage** [comment]
somtimes 400 or 500

**Comment by HeartWell** [comment]
And drop?

**Comment by TBMX2696** [comment]
Any idea why is that? I've been looking to fix the bug, but it seems to be more than just proxies.

**Comment by KevinLage** [comment]
> 
> 
> And drop?

because it sends only 1 request and then another one from a new proxy, with a new session. As soon as youtube detects that he isnt watching anymore they delete the viewert

**Comment by KevinLage** [comment]
> 
> 
> And drop?

yeah it will drop after some time

**Comment by HeartWell** [comment]
Maybe use private proxy? This fix problem drop?

**Comment by KevinLage** [comment]
no
