### ISSUE TITLE
I cant open the .py file

### ISSUE THREAD

**Issue by johntaxmi** [KevinLage/YouTube-Livestream-Botter#102]
I have python installed, but when i try to run the .py file its auto closing, how can i fix that?

**Comment by KevinLage** [comment]
open the file in your CMD and send me the screenshot

**Comment by bangbang113** [comment]
how do i open it in cmd?

**Comment by KevinLage** [comment]
open the cmd and drag & drop the file in it

**Comment by ayushkumar001** [comment]
how to get this exe version

**Comment by KevinLage** [comment]
https://github.com/KevinLage/YouTube-Livestream-Botter/releases
