### ISSUE TITLE
i need help setting up the bot through py

### ISSUE THREAD

**Issue by bangbang113** [KevinLage/YouTube-Livestream-Botter#105]
can anyone help?

**Comment by KevinLage** [comment]
install python3.7+ and all modules

**Comment by bangbang113** [comment]
what modules

**Comment by KevinLage** [comment]
requests and colorama

**Comment by bangbang113** [comment]
what is ur discord?

**Comment by KevinLage** [comment]
I dont have discord

**Comment by bangbang113** [comment]
![Annotation 2020-06-30 160630](https://user-images.githubusercontent.com/63899223/86172058-c5647f00-baeb-11ea-91c7-445d1c9784d1.png)

**Comment by KevinLage** [comment]
update pip

try to install it with --user at the end

**Comment by bangbang113** [comment]
![Annotation 2020-06-30 161152](https://user-images.githubusercontent.com/63899223/86172494-6d7a4800-baec-11ea-940a-546d39bb51a5.png)

**Comment by bangbang113** [comment]
is there a way you can show me how to do this

**Comment by KevinLage** [comment]
u wrote phython 

just copy & paste python -m pip install --upgrade pip

**Comment by bangbang113** [comment]
and on the one on my laptop is downloaded like this
![Capture](https://user-images.githubusercontent.com/63899223/86172894-145ee400-baed-11ea-8327-8875d06ebf7f.JPG)

**Comment by KevinLage** [comment]
something on your pc is blocking the connection to proxyscrape.com

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86173090-6ef84000-baed-11ea-8239-5ddd4e2e89d6.PNG)

**Comment by bangbang113** [comment]
what do i do now?

**Comment by KevinLage** [comment]
install the modules and run the script

**Comment by bangbang113** [comment]
i downloaded python and colorama already

**Comment by KevinLage** [comment]
and requests?

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86174122-17f36a80-baef-11ea-8124-868e39730f13.PNG)

**Comment by bangbang113** [comment]
same message

**Comment by bangbang113** [comment]
what requests?

**Comment by KevinLage** [comment]
what do you even type in the CMD?

**Comment by bangbang113** [comment]
py -m pip install then i drag the file and  press enter

**Comment by KevinLage** [comment]
which file??

**Comment by bangbang113** [comment]
the youtube live stream file i extracted it and put it on my desktop

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86174579-e9c25a80-baef-11ea-8f78-cbd5d9e3e304.PNG)

**Comment by KevinLage** [comment]
thats not how pip works.

you have to enter pip install MODULE
e.g. pip install requests
or pip install colorama

**Comment by bangbang113** [comment]
so type pip install module
then type pip install colorama

**Comment by KevinLage** [comment]
NO MODULE is just a place holder

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86174790-47ef3d80-baf0-11ea-93b3-71b34b96b2ec.PNG)

**Comment by bangbang113** [comment]
like that?

**Comment by KevinLage** [comment]
yeah

**Comment by bangbang113** [comment]
what do i do next?

**Comment by KevinLage** [comment]
install the other modules and start the script

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86174973-97356e00-baf0-11ea-91bc-479cc0298cac.PNG)

**Comment by KevinLage** [comment]
now start the script

**Comment by bangbang113** [comment]
![Capture](https://user-images.githubusercontent.com/63899223/86175101-c1872b80-baf0-11ea-89c1-044991c52a78.PNG)

**Comment by bangbang113** [comment]
how do i do this?

**Comment by KevinLage** [comment]
are u retarded? how am I supposed to know what do you want to use?

**Comment by bangbang113** [comment]
first lol my bad i didnt get that i was supposed to press a number lol i thought it was more steps damn why are you so mean....

**Comment by KevinLage** [comment]
then type 1 and press enter

**Comment by bangbang113** [comment]
thank you though ;/

**Comment by bangbang113** [comment]
now i have to find out whats blocking my pcs because its doing the same error code on both.

**Comment by KevinLage** [comment]
maybe your network or anti virus program
