### ISSUE TITLE
Error on exe

### ISSUE THREAD

**Issue by RezFn** [KevinLage/YouTube-Livestream-Botter#107]
[png2pdf (3).pdf](https://github.com/KevinLage/YouTube-Livestream-Botter/files/4853621/png2pdf.3.pdf)

keep getting this error once i drag the proxys.txt and put the ID plz help

**Comment by KevinLage** [comment]
upload the png file, not the pdf file

**Comment by RezFn** [comment]
![github](https://user-images.githubusercontent.com/67653411/86182328-c0a8c680-bafd-11ea-8b48-52d15adc9b0f.png)
![gith](https://user-images.githubusercontent.com/67653411/86182353-ca322e80-bafd-11ea-9450-d7890f400c44.png)

**Comment by KevinLage** [comment]
something on your PC/Network is blocking the connection to proxyscrape.com

**Comment by RezFn** [comment]
alright thanks:) used vpn worked perfectly
