### ISSUE TITLE
When in IDLE i want run bot its not working

### ISSUE THREAD

**Issue by IdkMaybeGamer** [KevinLage/YouTube-Livestream-Botter#108]
![image](https://user-images.githubusercontent.com/67760201/86402646-77e34000-bcac-11ea-97db-9d6717990913.png)

**Comment by KevinLage** [comment]
open your cmd and type "pip install requests" and "pip install colorama"

**Comment by 9ofe** [comment]
if your windows just use this https://github.com/KevinLage/YouTube-Livestream-Botter/releases/download/1.4/YouTube-Livestream-Botter-master.zip

Also Kevin is there a way to contact you ? maybe twittet, telegram . ?

**Comment by KevinLage** [comment]
telegram @overwrote
