### ISSUE TITLE
Stopped working after some days ( ERRORS ) 

### ISSUE THREAD

**Issue by Mirko1926** [KevinLage/YouTube-Livestream-Botter#11]
I have used it for days and it worked fine, but in the last hour every time I insert the id it shows this error : 
<img width="1280" alt="Schermata 2019-11-06 alle 23 31 16" src="https://user-images.githubusercontent.com/39387987/68343725-b9a3f280-00ed-11ea-977e-65738d6207d7.png">
got any fix?

**Comment by KevinLage** [comment]
I have no idea why. Does the python version work
