### ISSUE TITLE
Bot is not working...

### ISSUE THREAD

**Issue by VARboosted** [KevinLage/YouTube-Livestream-Botter#110]
Bot is not working
proxyscrape.com works
https://prnt.sc/tex3t3

**Comment by KevinLage** [comment]
do you use the exe or python?

**Comment by VARboosted** [comment]
exe

**Comment by Aymeriich** [comment]
in py dont work to, it start like 0 to 30 and then get stuck there

**Comment by Raz92** [comment]
My bot is not working

**Comment by Raz92** [comment]
Please help me

**Comment by Raz92** [comment]
How to use EXE AND PY FILE

**Comment by Raz92** [comment]
I have no Idea
