### ISSUE TITLE
it works fine but after 5 min it Decreases

### ISSUE THREAD

**Issue by newman43** [KevinLage/YouTube-Livestream-Botter#114]
it works fine but after 5 min it Decreases
then go up then decreases
some streamers stay at 1k viewers for hours (using bots )
how can i make it stay at hi numbers ? ( i tried adding alot of https proxies sometimes i got 600 viewers but after 5 min it decreases to 60 70
please help what i am doing wrong
all proxies added  works fine  and have been cheeked

**Comment by KevinLage** [comment]
thats a common issue and I have the same problem. There is no fix for it

**Comment by newman43** [comment]
> thats a common issue and I have the same problem. There is no fix for it

ohh  it is ok 
 it was a great code  and you did a good job  on it  
thank you  sir
