### ISSUE TITLE
Connection Forcibly closed

### ISSUE THREAD

**Issue by avas1025** [KevinLage/YouTube-Livestream-Botter#124]
Hi Kevin, first of all thank you for this.

Unfortunately, it's not working on me. I already tried 2 laptops with win10 and win7 and they have the same issue

see attached
![botter](https://user-images.githubusercontent.com/26940194/88464910-3cace900-cec7-11ea-9558-987d9d635528.JPG)

Thanks!

**Comment by KevinLage** [comment]
looks like u didnt entered 1 or 2 for the proxy loading option

**Comment by avas1025** [comment]
Now I just pressed 1, still the same error
![botter](https://user-images.githubusercontent.com/26940194/88465098-c7421800-cec8-11ea-9b27-30b712edeba8.JPG)

**Comment by KevinLage** [comment]
make sure that you can access these sites in your browser

https://api.proxyscrape.com
https://www.proxy-list.download/api/v1/get?type=https&anon=elite

**Comment by avas1025** [comment]
I cannot access both, what do you think is the problem? I have MS Security and malwarebytes

proxyscrape.com
![image](https://user-images.githubusercontent.com/26940194/88465198-be057b00-cec9-11ea-89a7-0256741fbe24.png)

https://www.proxy-list.download/api/v1/get?type=https&anon=elite
![image](https://user-images.githubusercontent.com/26940194/88465204-c8c01000-cec9-11ea-91ea-4eeb451ecc62.png)

**Comment by KevinLage** [comment]
try to disable your AV to access these sites

**Comment by avas1025** [comment]
still not working or I cannot access the 2 websites... I already turned off my anti virus and closed malwarebytes.

I'm in Saudi Arabia by the way... do you think they blocked the proxies?

**Comment by KevinLage** [comment]
could be possible

try to use a VPN

**Comment by avas1025** [comment]
Hi Kevin, just wanted to let you know that it's working when I used a VPN. I think this country prevents proxies...I have a question though, can I still use youtube while this is running?

**Comment by KevinLage** [comment]
yeah you should still be able to use youtube without any problems
