### ISSUE TITLE
I get an error when i run the script please fix this 

### ISSUE THREAD

**Issue by ashdc125** [KevinLage/YouTube-Livestream-Botter#13]
ID?
a27UN-MQXZk
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    token = input("ID?\n")
  File "<string>", line 1, in <module>
NameError: name 'a27UN' is not defined

**Comment by KevinLage** [comment]
whats your OS?

**Comment by ashdc125** [comment]
It is windows

**Comment by TheyLoveJay** [comment]
how do i run it lol I'm new srry

**Comment by KevinLage** [comment]
are u using the .exe or .py?

**Comment by ashdc125** [comment]
Py
