### ISSUE TITLE
How to get 1k viewers ??

### ISSUE THREAD

**Issue by kenzo8989** [KevinLage/YouTube-Livestream-Botter#174]
please help, I only get 100 - 300 viewers with a premium proxy from a premium proxy scrape.com ? can anyone help? I need up 1k viewers for my stream youtube

**Comment by Armeliot** [comment]
нужно больше прокси

**Comment by kenzo8989** [comment]
> нужно больше прокси

How much proxy, i can get 1k viewers ??

**Comment by Armeliot** [comment]
2-3к  рабочих

**Comment by Armeliot** [comment]
и если я не ошибаюсь то нужны sosks 4

**Comment by Armeliot** [comment]
SOCKS4*

**Comment by kenzo8989** [comment]
> SOCKS4*

okay, thank you, I'll try, what should I use premium socks4 proxy or free ?? and a good web to buy a premium proxy do you have any recommendations?

**Comment by Armeliot** [comment]
я использовал бесплатные, сейчас попробую повторно запустить накрутку на трансляцию, посмотрю на результат

**Comment by Armeliot** [comment]
короче, когда запускаешь там есть выбор прокси, http, socks4 и далее,   но я выбирал socks4 и у меня было максимум 300 человек. но они не долго держатся на стриме, примерно 5 минут, возможно это изза прокси socks4 и стоит попробовать SOCKS5, HTTPS или HTTP. Но покупать платные не обязательно так так может нестабильно работать
