### ISSUE TITLE
Seems need Update brother

### ISSUE THREAD

**Issue by Raz92** [KevinLage/YouTube-Livestream-Botter#177]
Seems need Update brother Youtuber Update ouctuber last week please update the exe file

**Comment by Raz92** [comment]
Please help me

**Comment by ghost** [comment]
so many stupid people here from nulled damn. Bot works without problems download the github repo and start the py file with python

**Comment by qveenqueenie** [comment]
> so many stupid people here from nulled damn. Bot works without problems download the github repo and start the py file with python 

Ill try that.. Is there any way i can get in contact with you for help as well just incase? Any help would be appreciated im not exactily the brightnest when it comes to tech... It worked perfectly like 2 months ago but now it doesnt... Can i get a hold of u to explain and see if maybe you can help with anything?

**Comment by ghost** [comment]
> > so many stupid people here from nulled damn. Bot works without problems download the github repo and start the py file with python
> 
> Ill try that.. Is there any way i can get in contact with you for help as well just incase? Any help would be appreciated im not exactily the brightnest when it comes to tech... It worked perfectly like 2 months ago but now it doesnt... Can i get a hold of u to explain and see if maybe you can help with anything?

sry i ain't doing that. just try to run the python file in terminal with python filename.py and if there is a error google it. You probably need to download and install the requirements but as i wrote you can just google the error messages you get from trying to run the python file

**Comment by KevinLage** [comment]
stop making tons of new issues wtf
