### ISSUE TITLE
Kevin can you make me bot live stream youtube for up 10k viewers, i will pay you special offer, please dm me.

### ISSUE THREAD

**Issue by kenzo8989** [KevinLage/YouTube-Livestream-Botter#179]
Kevin help me, make a bot for up 10k viewers . I will pay you special offers. Thanks please dm me.

**Comment by ghost** [comment]
I can @kenzo8989 
dm me on discord.gg/duck -> vanity only for few days ill be changing

**Comment by kenzo8989** [comment]
Halo bang ote
