### ISSUE TITLE
YouTube stream bot not working

### ISSUE THREAD

**Issue by goldenboy8872** [KevinLage/YouTube-Livestream-Botter#183]
your view bot thing does not work any more. every time i try to use it, this weird message pops up. I've tried downloading all your releases and none of them work. plz fix this bug and make a new release as soon as possible. i noticed other people have the same issue 
![Screenshot 2020-11-20 170833](https://user-images.githubusercontent.com/74799761/99861363-10426a00-2b53-11eb-97fe-65184b566700.png)

**Comment by goldenboy8872** [comment]
also i dont know how to do coding and crap so plz give me the answers in simple terms

**Comment by Lordbeatmeater69** [comment]
Hey golden im not the maker but the way i get it to work now is with a vpn. views dont stick anymore and watch time wont count either.

**Comment by KevinLage** [comment]
mcafee blocks the requests

**Comment by Lordbeatmeater69** [comment]
i dont have mcafee installed

**Comment by KevinLage** [comment]
MCaffe is blocking something either system wide or network wide. Its not a issue from the bot
