### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AisakaMegumi** [KevinLage/YouTube-Livestream-Botter#186]
Not working on repl,it, how to fix?

**Comment by KevinLage** [comment]
never used repl.it, just run it on your PC and it should run just fine

**Comment by Raz92** [comment]
Not working

**Comment by Raz92** [comment]
.exe is not working properly

**Comment by AisakaMegumi** [comment]
> never used repl.it, just run it on your PC and it should run just fine

i try on PC but Botted only 0? how to fix this?

**Comment by reinskay** [comment]
> 
> 
> > never used repl.it, just run it on your PC and it should run just fine
> 
> i try on PC but Botted only 0? how to fix this?

yeah me too.. pls update :(

**Comment by hippy4200** [comment]
Botting wont go pass 0 mark please update

**Comment by hippy4200** [comment]
> > > never used repl.it, just run it on your PC and it should run just fine
> > 
> > 
> > i try on PC but Botted only 0? how to fix this?
> 
> yeah me too.. pls update :(

Still not working?

**Comment by KevinLage** [comment]
Still works fine on my machine not sure what the problem is on your end. Maybe the proxys are dead or you entered a wrong ID

**Comment by hippy4200** [comment]
I was using it lastnight it was working fine then outta no where it wont
work now..
