### ISSUE TITLE
???

### ISSUE THREAD

**Issue by hippy4200** [KevinLage/YouTube-Livestream-Botter#198]
When will there be a new version or update????

**Comment by GloomyJack** [comment]
Hippy stop being asshole. You receive software for free and u behave like an idiot. If he plans to fix it, then he will when he'll have time for it. Stop spamming so much crap.

**Comment by hippy4200** [comment]
> Hippy stop being asshole. You receive software for free and u behave like an idiot. If he plans to fix it, then he will when he'll have time for it. Stop spamming so much not being a ass or anything just keep up with the program ĺ
