### ISSUE TITLE
is not defined error 

### ISSUE THREAD

**Issue by ATxAnon404** [KevinLage/YouTube-Livestream-Botter#23]
Traceback (most recent call last):
  File "YouTube Livestream Botter.py", line 23, in <module>
    token = input("ID?\n")
  File "<string>", line 1, in <module>
NameError: name 'keCf1v_vr1U' is not defined

**Comment by MrKinauJr** [comment]
You used the .EXE or the .PY file?
And did you ever update the Botter?

**Comment by harcheema** [comment]
hi When I make .py to .exe then exe file flashed n closed ?? Please Solve my Issue

**Comment by KevinLage** [comment]
please open the .exe with the cmd and send us a screenshot

**Comment by harcheema** [comment]
![botted not count](https://user-images.githubusercontent.com/59693823/72198226-74cf6b80-3450-11ea-8f87-102591a19a33.png)
Hi Bro Botted Not Count . Where is Problem ?

**Comment by KevinLage** [comment]
do you have the latest version?

**Comment by KevinLage** [comment]
check out the new update
