### ISSUE TITLE
I would like to make this thing even better

### ISSUE THREAD

**Issue by Danteswap27** [KevinLage/YouTube-Livestream-Botter#24]
Hello Kevin , if you read this i have some suggestion on improving this tool , i see you removed the exe because of some reasons but thats fair enough, what i want is to have an option to change the proxy url or to manually provide a txt file with proxies in that way someone can use their private proxies too, also in the header where you provide a user agent ,there i want to suggest you something  similar to the proxy file where user can provide a txt file with different user agents line by line , in that way it would be more good of a tool , if you are are reading this reply back so that i can provide some code ideas for the above , i am no good ad coding and the exe i build after modifying the py file provided is not working to , thats why i need you to help . reply back

**Comment by KevinLage** [comment]
1. I just moved the exe to releases (https://github.com/KevinLage/YouTube-Livestream-Botter/releases/tag/1.1)
2. I already started adding the proxy feature but I dont have much freetime rn
3. The problem is many user agents dont work

**Comment by Danteswap27** [comment]
1. Oh Just Noticed That While Surfing On Mobile Thanks For The Direction.

2.Thanks For The Precious work I really appreciate that , if you r open for suggestions , then make the proxy feature work like this so that user have three choices 1st run tool with default proxy scrape proxies and 2. to provide a different proxy site link other than proxyscrape , and 3. To manually provide a txt file with users own private or free proxies.,

3.Oh So Some Fail to work ok lets put this feature aside for now.

4. Sorry to ask this but the exe is working fine but the provided py file doesn't seem to work , I would like to modify the script a bit a test new features but the default py file doesn't seem to work , and after providing the token and threads the tool seems to go in a loop and the Boted text In Console Seems To flicker and stays at 0 . and doesn't work can you test that at you end if the py file is working or not , if it is working then what extra libraries I have to import and install for it to work . It would be a time save if I can successfully implement some features and post hem here after they seem to work in py file . thanks for replying

**Comment by KevinLage** [comment]
2. 
![grafik](https://user-images.githubusercontent.com/43577910/72224167-6465e080-3577-11ea-9595-79338080e5b6.png) rn working on socks4 and 5 support

4. idk why some users have problems with the py file, everything works for me

**Comment by Danteswap27** [comment]
2. Wow Thats Epic Thanks For Working . I will Wait for That .

4. Ok So For The py file i will reinstall python ,Fresh Install And Then I will Run The Script , But Now This Time I will Only Import The Libraries That You will Mention in your reply , may be i am missing any libraries or something, SO Lets Give It A Try , Can You Please Mentions all the libraries that needs to be imported including the once in the py file . I Will Come Back After Testing

**Comment by KevinLage** [comment]
I think you need threading, queue, platform, requests and colorama maybe some of them are already preinstalled

**Comment by settooo** [comment]
For me, it's working very well. Good job Kevin

**Comment by Danteswap27** [comment]
> For me, it's working very well. Good job Kevin

**Comment by Danteswap27** [comment]
Ok For ME Nothing Is Working for the py script , May be the python v3.8(64 bit) is the problem Or may Be Not , But FOr Now Lets close this thread , i ll reopen once i get some sugggestions or got any update on the problem on why the py is not working for me , Thanks Kevin for the replies , I hope Next update comes soon with custom proxy support, For Now lets close this .

**Comment by Danteswap27** [comment]
Ok For ME Nothing Is Working for the py script , May be the python v3.8(64 bit) is the problem Or may Be Not , But FOr Now Lets close this thread , i ll reopen once i get some sugggestions or got any update on the problem on why the py is not working for me , Thanks Kevin for the replies , I hope Next update comes soon with custom proxy support, For Now lets close this .

**Comment by KevinLage** [comment]
test the new update

**Comment by Danteswap27** [comment]
Ya i tested the new Update but the result is same with the py script as soon as i enter the number of threads , it goes into some kinda odd loop against its functionality , I have attached a video you can see what is happening ,the video is short but i waited like 15 minutes on that botted =0 screen lol. Its something else or may be some problem with latest python version . dont know for sure, but ya exe is working fine as intende, its just the py thats causing problem.

here is the video

[My Video.zip](https://github.com/KevinLage/YouTube-Livestream-Botter/files/4060652/My.Video.zip)

**Comment by skshivamsk** [comment]
hey, can you make like 1K watching? I mean it should require better proxies or it can't do?

**Comment by Medic78** [comment]
Hello i have a problem with this program, it gives me a maximum of 30 bots, regardless of whether I enter 1000,100 or any other ... does anyone know what the problem may be? Maybe I have too low internet speed? (150 mb / s) help me pleas

**Comment by KevinLage** [comment]
> 
> 
> hey, can you make like 1K watching? I mean it should require better proxies or it can't do?

I think you just need HQ proxies

**Comment by KevinLage** [comment]
> 
> 
> Hello i have a problem with this program, it gives me a maximum of 30 bots, regardless of whether I enter 1000,100 or any other ... does anyone know what the problem may be? Maybe I have too low internet speed? (150 mb / s) help me please

I have about 25mbit and everything works fine

**Comment by KevinLage** [comment]
> 
> 
> Ya i tested the new Update but the result is same with the py script as soon as i enter the number of threads , it goes into some kinda odd loop against its functionality , I have attached a video you can see what is happening ,the video is short but i waited like 15 minutes on that botted =0 screen lol. Its something else or may be some problem with latest python version . dont know for sure, but ya exe is working fine as intende, its just the py thats causing problem.
> 
> here is the video
> 
> [My Video.zip](https://github.com/KevinLage/YouTube-Livestream-Botter/files/4060652/My.Video.zip)

maybe your IP is blocked by proxyscrape

**Comment by Danteswap27** [comment]
> > Ya i tested the new Update but the result is same with the py script as soon as i enter the number of threads , it goes into some kinda odd loop against its functionality , I have attached a video you can see what is happening ,the video is short but i waited like 15 minutes on that botted =0 screen lol. Its something else or may be some problem with latest python version . dont know for sure, but ya exe is working fine as intende, its just the py thats causing problem.
> > here is the video
> > [My Video.zip](https://github.com/KevinLage/YouTube-Livestream-Botter/files/4060652/My.Video.zip)
> 
> maybe your IP is blocked by proxyscrape
> 
> edit: nvm I think you forgot to install some libs

may be , I have Installed All The Above Libs That You Have Mentioned , If you forgot to Mentioned Any Libs in Your Msg Then Please Mention them Here In Your Next Msg , Its Gonna be fun If the Py Works And My End.

**Comment by TheDJKitty** [comment]
> 
> 
> > > Ya i tested the new Update but the result is same with the py script as soon as i enter the number of threads , it goes into some kinda odd loop against its functionality , I have attached a video you can see what is happening ,the video is short but i waited like 15 minutes on that botted =0 screen lol. Its something else or may be some problem with latest python version . dont know for sure, but ya exe is working fine as intende, its just the py thats causing problem.
> > > here is the video
> > > [My Video.zip](https://github.com/KevinLage/YouTube-Livestream-Botter/files/4060652/My.Video.zip)
> > 
> > 
> > maybe your IP is blocked by proxyscrape
> > edit: nvm I think you forgot to install some libs
> 
> may be , I have Installed All The Above Libs That You Have Mentioned , If you forgot to Mentioned Any Libs in Your Msg Then Please Mention them Here In Your Next Msg , Its Gonna be fun If the Py Works And My End.

I have found a fix for the botted number staying at 0.
find the def FormatProxy(self): and replace the proxyOutput with this code.
**proxyOutput = {'https' :'https://'+self.get_proxy()}**

**Comment by Danteswap27** [comment]
> Ya i tested the new Update but the result is same with the py script as soon as i enter the number of threads , it goes into some kinda odd loop against its functionality , I have attached a video you can see what is happening ,the video is short but i waited like 15 minutes on that botted =0 screen lol. Its something else or may be some problem with latest python version . dont know for sure, but ya exe is working fine as intende, its just the py thats causing problem.
> here is the video
> My Video.zip
> 
> maybe your IP is blocked by proxyscrape
> edit: nvm I think you forgot to install some libs
> 
> may be , I have Installed All The Above Libs That You Have Mentioned , If you forgot to Mentioned Any Libs in Your Msg Then Please Mention them Here In Your Next Msg , Its Gonna be fun If the Py Works And My End.
> 
> I have found a fix for the botted number staying at 0.
> find the def FormatProxy(self): and replace the proxyOutput with this code.
> proxyOutput = {'https' :'https://'+self.get_proxy()}

Wow That Really Fixed The Problem That Was Stopping The Script From Working Now The Fun Begins  Lets Test Some New Things Now.

**Comment by jonathanbj1977** [comment]
hi everyone and thanks keving and all other who work on this awesone stream botter :)
my apologies i don't want to bother anyone i'm nob on this lol
but are you guys are trying to do something like viewerlabs??
will be NIIIIIIICE!

**Comment by adamzatnika** [comment]
kevin help me, 

how can change proxy with custom proxy i was buy proxy premium, but I don't know what I should change

maybe anyone can help?

**Comment by KevinLage** [comment]
change the URL in the python file

**Comment by adamzatnika** [comment]
> change the URL in the python file

no changes, display only 0 boot

**Comment by Danteswap27** [comment]
> change the URL in the python file

Hi kevin Glad To See You Here , Ok So How is The Socks proxies support Going on , is It Coming Soon Or Will It Take More Time, Also Do You Have Any Alternate for Permium Proxies That u use and Will Work Flawless On YouTube , I mean I have Not Checked proxy scrape premium but sooon will , so if you can suggest something good that works so I can try that instead of proxyscrape . Your Call.

**Comment by Danteswap27** [comment]
> change the URL in the python file
> 
> no changes, display only 0 boot

Download The Latest version of python fine and replace these with your proxy URL "urls = ["https://api.proxyscrape.com/?request=getproxies&proxytype=http&timeout=10000&ssl=yes","**_https://www.proxy-list.download/api/v1/get?type=https&anon=elite*_*"]"

**Comment by adamzatnika** [comment]
hi kevin yt bot not work now please fix it help thanks

**Comment by Danteswap27** [comment]
> hi kevin yt bot not work now please fix it help thanks

Whats the problem ?

**Comment by KevinLage** [comment]
> 
> 
> > change the URL in the python file
> 
> Hi kevin Glad To See You Here , Ok So How is The Socks proxies support Going on , is It Coming Soon Or Will It Take More Time, Also Do You Have Any Alternate for Permium Proxies That u use and Will Work Flawless On YouTube , I mean I have Not Checked proxy scrape premium but sooon will , so if you can suggest something good that works so I can try that instead of proxyscrape . Your Call.

I dont know why but socks arent really working 

allready tried :/

**Comment by Danteswap27** [comment]
> > > change the URL in the python file
> > 
> > 
> > Hi kevin Glad To See You Here , Ok So How is The Socks proxies support Going on , is It Coming Soon Or Will It Take More Time, Also Do You Have Any Alternate for Permium Proxies That u use and Will Work Flawless On YouTube , I mean I have Not Checked proxy scrape premium but sooon will , so if you can suggest something good that works so I can try that instead of proxyscrape . Your Call.
> 
> I dont know why but socks arent really working
> 
> allready tried :/

Ok No problem , Http is working I am Just Confused In choosing a premium proxy provider, They All Have Bandwidth Limit And I Dont Know How Much BandWidth Our Bot Will Consume In One Session of an hour With 1000 Bottted Views , Can You Suggest Something ?

**Comment by 9ofe** [comment]
No don't buy limited bandwidth proxies
the bot will use like 1gb per minute something like or even more 

and something else if u used premium proxies u will get the 1k views instantly with 1k proxies and u will lose the 1k views instantly after like 5mins

**Comment by KevinLage** [comment]
> No don't buy limited bandwidth proxies
> the bot will use like 1gb per minute something like or even more
> 
> and something else if u used premium proxies u will get the 1k views instantly with 1k proxies and u will lose the 1k views instantly after like 5mins

why do you think it will take more then 1gb per min do you even know how the bot works?

**Comment by 9ofe** [comment]
i know that because i tried it :))

**Comment by KevinLage** [comment]
one request is about 500byte I dont think that you that you send ~2147483 per minut

**Comment by Danteswap27** [comment]
> one request is about 500byte I dont think that you that you send ~2147483 per min

Oh wait a min. R u sure its 500 bytes for 1 request not 500 kb for 1 request. Well if kevin says that then i will test out some premium proxies. And if it really is 500 byte for a request then we'll it's more then enough. Kevin can you please confirm that it's really 500 bytes to 1024 bytes for a request. Your r the mind behind the awesome tool. So at this point I believe you for your words. Can you confirm? If yes then i am going to test multiple providers in the span of the month.

**Comment by KevinLage** [comment]
there are 2 requests 

1 to the livestream itself (50kb) and then there is a request to the watchtime api 500bytes

**Comment by Danteswap27** [comment]
> there are 2 requests
> 
> 1 to the livestream itself (50kb) and then there is a request to the watchtime api 500bytes

Hmm So Thats In total 51KB For 1 Single Request So If Thats Correct Then We Can Do 20K Requests For 1 GB Of Bandwidth Roughly , AM I Right ? If Yes Then Wow Amazing Work Kevin .

**Comment by DannyDavitoo** [comment]
Hey @KevinLage Great work on this! i was wondering if you could create a bot like this that would work on facebook live streams? Obviously for a price.

Thanks!

**Comment by sullyjake20** [comment]
https://gyazo.com/074298cba7ab689e16cbfd9e8cdf22fe    but nothing happens on the livestream?? can someone help me plssss
