### ISSUE TITLE
The viewer gradually decreases to a 0 after 5 minute-ish livestream botting.

### ISSUE THREAD

**Issue by ivanderboris** [KevinLage/YouTube-Livestream-Botter#25]
as the title says, i've tried once to see if this works. It works great! but the problem is after some minutes the viewers dropped rapidly to zero.

Any idea why this happens? and how to limit the viewer to 50 for example?

**Comment by KevinLage** [comment]
Im aware of this issue but I have no idea how I can fix it

**Comment by ivanderboris** [comment]
I do think that the rapidly increased viewer triggers something on the Youtube side.

What about make it like the viewer gradually increases overtime? and what does the threads do?

**Comment by KevinLage** [comment]
if you start it with 200 threads its like you open the programm 200 times
