### ISSUE TITLE
broken 

### ISSUE THREAD

**Issue by Vixxy223** [KevinLage/YouTube-Livestream-Botter#26]
wont open

**Comment by KevinLage** [comment]
exe or py?

**Comment by Vixxy223** [comment]
PY

**Comment by KevinLage** [comment]
can u send me the error?

**Comment by Vixxy223** [comment]
It just doesnt open
it closes once a see a cmd

**Comment by KevinLage** [comment]
open it in the cmd

**Comment by Vixxy223** [comment]
open it with cmd prompt?

**Comment by KevinLage** [comment]
yes

**Comment by Vixxy223** [comment]
i get an error saying this file type cant be associated with this software

**Comment by KevinLage** [comment]
can u send me an screenshot?

**Comment by Vixxy223** [comment]
sure

**Comment by Vixxy223** [comment]
![image](https://user-images.githubusercontent.com/60368647/73221060-f05a3980-412d-11ea-8d40-42fd5060b8d0.png)

**Comment by KevinLage** [comment]
Do you even have python installed?

**Comment by Vixxy223** [comment]
yes

**Comment by Vixxy223** [comment]
![image](https://user-images.githubusercontent.com/60368647/73221102-0cf67180-412e-11ea-8c9e-473047a98e55.png)

**Comment by Vixxy223** [comment]
that python

**Comment by KevinLage** [comment]
did you started it with "py" in the cmd?

**Comment by Vixxy223** [comment]
what do you mean by that?

**Comment by KevinLage** [comment]
did u entered just "youtube.py" or "py youtube.py" in the cmd

**Comment by KevinLage** [comment]
btw. does the exe work?

**Comment by Vixxy223** [comment]
no

**Comment by KevinLage** [comment]
what happens if you start the .exe?

**Comment by Vixxy223** [comment]
it crashes immediately

**Comment by KevinLage** [comment]
same error?

**Comment by Vixxy223** [comment]
yea it just closes and opens

**Comment by KevinLage** [comment]
weird

**Comment by Vixxy223** [comment]
can you send a working one

**Comment by Vixxy223** [comment]
?

**Comment by KevinLage** [comment]
the latest version on github works for me

**Comment by Vixxy223** [comment]
how

**Comment by Vixxy223** [comment]
what python do i download

**Comment by Vixxy223** [comment]
i have 3.8.1

**Comment by KevinLage** [comment]
you dont need python for the exe
