### ISSUE TITLE
Is it gonna be possible to add custom proxies?

### ISSUE THREAD

**Issue by deadlii** [KevinLage/YouTube-Livestream-Botter#27]
I can get up to 150 viewers then it drops to 30 viewers i would like to use my own proxies if possible?

**Comment by Danteswap27** [comment]
> I can get up to 150 viewers then it drops to 30 viewers i would like to use my own proxies if possible?

Ya you will be Able To Use Custom Proxies , Just Give Kevin Some Time He is Busy With Other Projects So Next Update Will Take A while ,
