### ISSUE TITLE
Bot isn't working "botted 0"

### ISSUE THREAD

**Issue by aslisk** [KevinLage/YouTube-Livestream-Botter#28]
Bot isn't working "botted 0" always

**Comment by KevinLage** [comment]
do you use python or .exe?

**Comment by legolasek** [comment]
same problem, yesterday works fine but today botted 0
.exe

**Comment by KevinLage** [comment]
maybe proxyscrape is down rn or you got blocked

**Comment by legolasek** [comment]
any live stream (not only mine) so i not blocked

**Comment by aslisk** [comment]
its not working in any way .py .exe / windows ubuntu - not working anywhere

**Comment by KevinLage** [comment]
testing it rn and it works

**Comment by legolasek** [comment]
yea, now its working :D

**Comment by KevinLage** [comment]
okay great
