### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by OHSMASTER** [KevinLage/YouTube-Livestream-Botter#29]
I couldn't compile the script!
Would you help me?

**Comment by KevinLage** [comment]
can u send me the error?

**Comment by OHSMASTER** [comment]
https://prnt.sc/r585fh

**Comment by KevinLage** [comment]
hm weird, Im using pyinstaller too and everything works fine

**Comment by Boypshyco** [comment]
![image](https://user-images.githubusercontent.com/32366249/74949958-04454280-5431-11ea-9188-d8c8f80cf2de.png)

Use this version of python.

**Comment by KevinLage** [comment]
python3.7 should be fine too

**Comment by OHSMASTER** [comment]
I'm using 3.8.1

**Comment by KevinLage** [comment]
should work too

**Comment by KevinLage** [comment]
ty py -m PyArmor -F yt.py

**Comment by KevinLage** [comment]
oh not PyArmor PyInstaller

**Comment by KevinLage** [comment]
py -m PyInstaller-F yt.py

works for me

**Comment by OHSMASTER** [comment]
https://prnt.sc/r58bq8

now he is showing this

**Comment by OHSMASTER** [comment]
py -m PyInstaller-F yt.py
this command for me does not work
 pyinstaller -F Ja.py
this one worked

**Comment by KevinLage** [comment]
> 
> 
> https://prnt.sc/r58bq8
> 
> now he is showing this

yeah you still need to install all modues

**Comment by OHSMASTER** [comment]
how to do this?

**Comment by KevinLage** [comment]
pip install *module name*

**Comment by OHSMASTER** [comment]
ok,I installed the module and it keeps showing the same error :(

**Comment by KevinLage** [comment]
yeah you need to rebuild the exe

**Comment by OHSMASTER** [comment]
I just did it. Still giving the same problem :(

**Comment by Boypshyco** [comment]
lol :v

**Comment by OHSMASTER** [comment]
can be compiled for me and switch the proxy link to this one (https://pastebin.com/0RgdaYWc)

**Comment by OHSMASTER** [comment]
https://prnt.sc/r59xjn
I installed it on a virtual machine and now it is giving these errors

**Comment by OHSMASTER** [comment]
can you help me?

**Comment by KevinLage** [comment]
send me the python file and I can compile it for you

**Comment by OHSMASTER** [comment]
`import os
import random
import string
import threading
import time
from queue import Queue
import platform

import requests
from colorama import Fore, init

intro = """
███████╗████████╗██████╗ ███████╗ █████╗ ███╗   ███╗      ██████╗  ██████╗ ████████╗████████╗███████╗██████╗ 
██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔══██╗████╗ ████║      ██╔══██╗██╔═══██╗╚══██╔══╝╚══██╔══╝██╔════╝██╔══██╗
███████╗   ██║   ██████╔╝█████╗  ███████║██╔████╔██║█████╗██████╔╝██║   ██║   ██║      ██║   █████╗  ██████╔╝
╚════██║   ██║   ██╔══██╗██╔══╝  ██╔══██║██║╚██╔╝██║╚════╝██╔══██╗██║   ██║   ██║      ██║   ██╔══╝  ██╔══██╗
███████║   ██║   ██║  ██║███████╗██║  ██║██║ ╚═╝ ██║      ██████╔╝╚██████╔╝   ██║      ██║   ███████╗██║  ██║
╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝      ╚═════╝  ╚═════╝    ╚═╝      ╚═╝   ╚══════╝╚═╝  ╚═╝
"""

print(intro)

if platform.system() == "Windows": #checking OS
    clear = "cls"
else:
    clear = "clear"

token = input("ID?\n")
url= "https://m.youtube.com/watch?v=" + token
url2 = "https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage&cpn=AiWtf2fjIwVS2MeQ&docid=" + token + "&ver=2&cmt=7926.045&ei=igGSXce3IM2NgAfasp-ABg&fmt=133&fs=0&rt=1096.007&of=L_224b5BokWsQ5UWgAws_w&euri&lact=2837&live=dvr&cl=271684942&state=playing&vm=CAEQABgEKhhJc0gwZ2w0QmFfbTBWSXlWNm9ITmRRPT0&volume=100&c=MWEB&cver=2.20190928.07.00&cplayer=UNIPLAYER&cbrand=apple&cbr=Safari%20Mobile&cbrver=12.1.15E148&cmodel=iphone&cos=iPhone&cosver=12_2&cplatform%20=MOBILE&delay=5&hl=ru_RU&cr=DE&rtn=1396&afmt=140&lio=1556394045.182&idpj=&ldpj=&rti=1096&muted=0&st=7626.045&et=7926.045 "
class main(object):
    def __init__(self):
        self.combolist = Queue()
        self.Writeing = Queue()
        self.printing = []
        self.botted = 0
        self.combolen = self.combolist.qsize()

    def printservice(self): #print screen
        while True:
            if True:
                os.system(clear)
                print(Fore.LIGHTCYAN_EX + intro + Fore.LIGHTMAGENTA_EX)
                print(
                    Fore.LIGHTCYAN_EX + f"Botted:{self.botted}\n")
                for i in range(len(self.printing) - 10, len(self.printing)):
                    try:
                        print(self.printing[i])
                    except (ValueError, Exception):
                        pass
                time.sleep(0.5)
a = main()
class proxy():

    def update(self):
        while True:
            url = "https://8bits.life/proxy"
            r = requests.get(url)

            self.splited = r.text.split("\r\n") #scraping and splitting proxies
            time.sleep(600)
    
    def get_proxy(self):
        random1 = random.choice(self.splited) #choose a random proxie
        return random1
    def FormatProxy(self):
	    proxyOutput = {'https':self.get_proxy()}
	    return proxyOutput

    def __init__(self):
        self.splited = []
        threading.Thread(target=self.update).start()
        time.sleep(3)

proxy1 = proxy()
def bot():
    while True:

        


        headers={
        "Host": "m.youtube.com",
        "Accept-Encoding": "gzip, deflate",
        "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8",
        "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
        "Connection": "close"
        }

        try:
            s = requests.session()
            s.get(url,headers=headers,proxies=proxy1.FormatProxy()) #stream request
            s.get(url2,headers=headers,proxies=proxy1.FormatProxy()) #api request

            a.botted += 1
        except:
            pass


time.sleep(7)
maxthreads = int(input("How many Threads? Recommended: 500 - 1000\n"))

threading.Thread(target=a.printservice).start()
num = 0
while num < maxthreads :
    num += 1
    threading.Thread(target=bot).start()


threading.Thread(target=bot).start()
`

**Comment by KevinLage** [comment]
https://x0.at/AxQ.exe
