### ISSUE TITLE
Proxies API integration

### ISSUE THREAD

**Issue by sanharchaoui** [KevinLage/YouTube-Livestream-Botter#32]
Thank you KevinLage for this wonderful program.

I tried the two version .py and .exe, the bot stop after few hours "4-6 hours max"
Maybe it's due to proxies.

Tried to integrate a new api with authorization Token but no success. get errors.
Is there away to help me out set it up.

New api :

import requests

response = requests.get("https://PROXYSITE/api/proxy/list/?page=1&countries=US-FR", headers={"Authorization": "Token <APIKEY>"})
response.json()

Thank you

**Comment by KevinLage** [comment]
add me KevinLage#7429
