### ISSUE TITLE
Ability to use your own proxy.

### ISSUE THREAD

**Issue by GIFUS** [KevinLage/YouTube-Livestream-Botter#33]
Hello. Will it be possible to use your proxies to cheat the viewers? Or the ability to combine your own proxies with proxyscrape?

**Comment by MaxJackson1** [comment]
Yes code it by your self :)

**Comment by MaxJackson1** [comment]
it have to be only the same output

**Comment by rafalohaki** [comment]
added possibility to add ur own proxy by url
