### ISSUE TITLE
Recommend youtube live

### ISSUE THREAD

**Issue by HeartWell** [KevinLage/YouTube-Livestream-Botter#39]
Hello, thx for script) I have question. YouTube not reccomens livestream if you have 500 views why?

**Comment by KevinLage** [comment]
??

**Comment by HeartWell** [comment]
The stream in Analytics will not be included in the recommendations.

**Comment by KevinLage** [comment]
and what should I do about it?

**Comment by HeartWell** [comment]
I just asked if it was possible)
