### ISSUE TITLE
[QUESTION] Modifying the script for other [better] proxy list apis

### ISSUE THREAD

**Issue by terminatorhd** [KevinLage/YouTube-Livestream-Botter#40]
Do you know if there is any other proxy sites that i can implement into the script?

ive tried using https://www.proxy-list.download/api/v1 though it seems to not be as efficient and was wondering if you got any advice or know of some better sites to use in tandem with proxyscrape

**Comment by redgamerclan** [comment]
this is free paid sites i got use it for the proxies list bro its more
active then  https://www.youtube.com/watch?v=cNnwWYhuxss this

**Comment by redgamerclan** [comment]
plz check ur main i send it with gmail ohk bro
