### ISSUE TITLE
How to set custom proxy list from pastebin?

### ISSUE THREAD

**Issue by tora3268** [KevinLage/YouTube-Livestream-Botter#41]
Which format to use to put in the url section
1. https://pastebin.com/dl/cdFeMmmG             
Or
2. https://pastebin.com/raw/cdFeMmmG

**Comment by KevinLage** [comment]
2.

**Comment by tora3268** [comment]
Thank you. Is it the right format for proxies with password?
23.54.32.762:452:login:pass

**Comment by KevinLage** [comment]
the bot doesnt support proxies with login

**Comment by tora3268** [comment]
Could you make it optional, like some lines to add in the .py file. I can run the .py file using anaconda in windows. Or to randomly pic the proxies from a text file.

**Comment by 9ofe** [comment]
if u want to use ur own proxies from .txt file 
make Line 61
            data = 'proxies.txt'

and create file with that name and put ur proxies.

**Comment by tora3268** [comment]
Thank you. Will the proxies with password work? I have 4G proxies in this format 23.54.32.762:452:login:pass

**Comment by harcheema** [comment]
> if u want to use ur own proxies from .txt file
> make Line 61
> data = 'proxies.txt'
> 
> and create file with that name and put ur proxies.

not worked bro .
