### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by miner232** [KevinLage/YouTube-Livestream-Botter#42]
stuck on botted:0
also sgestion to use an extrnal proxy list so it wil be ez to use custum proxys

**Comment by miner232** [comment]
let me correct myself ist not working on some lives and on some it does

**Comment by KevinLage** [comment]
are you sure that you only botted active livestreams?

**Comment by ef3f3ef43** [comment]
yo im new how i do i download this? i tried clone file but it does not show any exe or download im so confused can u give me a step by step

**Comment by tora3268** [comment]
Working fine.
