### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by Kellyfends007** [KevinLage/YouTube-Livestream-Botter#44]
Hello SIR, script does work ( please fix it

**Comment by KevinLage** [comment]
could you provide more informations?

**Comment by les0n** [comment]
@KevinLage Can you add new proxy pls

https://awmproxy.net/freeproxy_8d33e5da03cf74a.txt

**Comment by KevinLage** [comment]
just add the link yourself

**Comment by Kellyfends007** [comment]
> could you provide more informations?

Program does add new user to stream. Please try now test this program

**Comment by HeartWell** [comment]
> just add the link yourself

link awmproxy don't work in script.
