### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by BatDev0** [KevinLage/YouTube-Livestream-Botter#49]
https://www.virustotal.com/gui/file/b9c0e1c400a45f068e15506bb7e4dfa638ca6e03b29afa0390bf09015afb24d5/detection

**Comment by KevinLage** [comment]
??

**Comment by KevinLage** [comment]
Do you really think it's an virus because Virustotal shows 3 false positives from noname anti virus tools.
Its open source just check the code or compile it yourself xd

**Comment by DrWeabo** [comment]
@KevinLage she's a kid bro :v

**Comment by BatDev0** [comment]
> @KevinLage she's a kid bro :v

Way to assume my gender but okay. And I was just asking if it was.
