### ISSUE TITLE
bot stop working ?? 

### ISSUE THREAD

**Issue by jonathanbj1977** [KevinLage/YouTube-Livestream-Botter#50]
hello and thank you KevinLage and all who make this beautiful bot possible :)
do you know if this is normal ?? (z0Hei-7i6BU) youtube change something or bot stop working ?? thank you all very much and blessings to all

**Comment by tora3268** [comment]
Working fine.

**Comment by KevinLage** [comment]
make sure that you use the latest version since youtube fixed the old one

**Comment by jonathanbj1977** [comment]
thanks you bout :)
