### ISSUE TITLE
Does it keeps on downloading the proxies after sometime or downloads just in the start?

### ISSUE THREAD

**Issue by tora3268** [KevinLage/YouTube-Livestream-Botter#51]
Does it keeps on downloading the proxies after sometime or downloads just in the start? I am planning to compile the script with own proxies file which will be updated every 1 hour. Will the bot be able to re-download the proxies every 1 hour?

**Comment by KevinLage** [comment]
yes it updates / downloads the proxies every 5min

you can simply change the interval by changing the number in time.sleep()

**Comment by tora3268** [comment]
Amazing. Thank you for the wonderful script.
