### ISSUE TITLE
my apologies to all I do not want to bother anyone

### ISSUE THREAD

**Issue by jonathanbj1977** [KevinLage/YouTube-Livestream-Botter#53]
My English is not very good and i know this is a nice gifr from you guys :) (im ready if this change i will be client for sure lol)

but i'm really worried since yesterday, I don't know if I'm doing something wrong, I follow these steps 

1.0 Instructions for Windows (.exe / Executeable File)
Download the ".exe" variant of the program.
Double click or right click -> execute the file
Enter the ID of a youtube livestream
Enter an amount of threads
See the viewers rise!

2.0 Instructions for Windows/Linux (.py / Python)

3.0 Whats the ID of a Livestram?
YouTube URLs look something like this => https://www.youtube.com/watch?v=dsfsdefgdfdsf
Then dsfsdefgdfdsf would be the ID of the video. (with the latest version of the bot)

or I don't know, if something happen with YouTube (before 1 hour video was 1K Views easy lol)
the thing is that after getting 9k+Views 3k+Views and 1k+Views on Apr 15, 2020 
all my other videos are (68 Views ) (143 Views)  i no longer catch 700 Views not even with 11 hour long video lol
is this normal now or am I doing something wrong ?? 
https://imgur.com/a/SzON58Q
questions please:
We also need to run the bot.exe on the same pc we are streaming or any other pc ??
How many bot.exe can you run at the same time?
thanks you all :)

**Comment by jonathanbj1977** [comment]
yea this is sad not working for real, we need make some donation to kevin we need hwlp devs too.

**Comment by KevinLage** [comment]
did u tried to bot a video or a livestream?

**Comment by jonathanbj1977** [comment]
> did u tried to bot a video or a livestream?
bot is working again today (was only 0 when i open this issue)
i only I only use the bot for my stream (i stream for 12 or 14 hours everyday) right now i have (91 watching now Started streaming 9 hours ago + 3,034 Views stopped for a long time lol)
I really don't understand what happen now, before every time I finish my stream I had 6k-9k easy and fast (3k in 2 hours stream lol) but now is not same.Thanks you so much kevin for your work and help :)

**Comment by KevinLage** [comment]
no problem
