### ISSUE TITLE
basically no views anymore help please

### ISSUE THREAD

**Issue by jonathanbj1977** [KevinLage/YouTube-Livestream-Botter#57]
hi there is any problem with bot ?? before i get 4K or 5K Views, but now is only 100,300 Views for video since yesterday (i do not if it has anything to do with my monetization that started two days ago) someone with the same problem ?? thank you all very much again !!

**Comment by KevinLage** [comment]
do you use proxyscrape proxies?

**Comment by jonathanbj1977** [comment]
> do you use proxyscrape proxies?

nope I hope I'm not making a huge mistake lol

**Comment by KevinLage** [comment]
read #58
