### ISSUE TITLE
I am not getting views

### ISSUE THREAD

**Issue by anv2605** [KevinLage/YouTube-Livestream-Botter#58]
I started a live stream on YouTube and ran the bot because of the bot i got 74 viewers and I live streamed for 15mins. But once I opened YouTube studio there were no views or watchtime added to the live stream. Why is this happening ? I even opened the yt studio after 1 day still got no views or watchtime. Help !

**Comment by jonathanbj1977** [comment]
yep same here i see up to 300 viewers but not views or watchtime (ths happen before as well)

**Comment by KevinLage** [comment]
the bot is not for watchtime or many views its just for trolling some streamers watchtime or views never counted
