### ISSUE TITLE
Correct format for proxies from file

### ISSUE THREAD

**Issue by tora3268** [KevinLage/YouTube-Livestream-Botter#61]
Is it the correct format for proxies from file when we dont need proxies from url in the py script?
`class proxy():

    def update(self):
        while True:
            data = '"C:\Users\Administrator\Desktop\proxies.txt"'
            urls = []
            for url in urls:
                data += requests.get(url).text
                
            self.splited += data.split("\r\n") #scraping and splitting proxies
            time.sleep(300)
    
    def get_proxy(self):
        random1 = random.choice(self.splited) #choose a random proxie
        return random1
    def FormatProxy(self):
	    proxyOutput = {'https' :'https://'+self.get_proxy()}
	    return proxyOutput

    def __init__(self):
        self.splited = []
        threading.Thread(target=self.update).start()
        time.sleep(3)

proxy1 = proxy()`

However it is not working for me.

**Comment by KevinLage** [comment]
thats completely wrong

**Comment by tora3268** [comment]
> thats completely wrong

Could you please format it?
