### ISSUE TITLE
Will the py script work on linux vps?

### ISSUE THREAD

**Issue by tora3268** [KevinLage/YouTube-Livestream-Botter#62]
Will the py script work on linux vps?

**Comment by KevinLage** [comment]
should work but I only tested it on Ubuntu and Linux Mint

**Comment by tora3268** [comment]
Cool. I will update here after testing.

**Comment by tora3268** [comment]
> should work but I only tested it on Ubuntu and Linux Mint
On ubuntu 16 getting the following error. Could you prepare a ubuntu ready py file. It must be 5 minutes work for you.
![Screen Shot 2020-05-02 at 7 30 32 PM](https://user-images.githubusercontent.com/59962452/80866347-c32ca280-8cab-11ea-9b52-8b3356034dad.png)

**Comment by tora3268** [comment]
Syntax error showing on ubuntu 16. Could you prepare a ubuntu ready py file. It must be 5 minutes work for you.
error in the following
`    def printservice(self): #print screen
        while True:
            if True:
                os.system(clear)
                print(Fore.LIGHTCYAN_EX + intro + Fore.LIGHTMAGENTA_EX)
                print(
                    Fore.LIGHTCYAN_EX + f"Botted:{self.botted}\n")
                for i in range(len(self.printing) - 10, len(self.printing)):
                    try:
                        print(self.printing[i])
                    except (ValueError, Exception):
                        pass
                time.sleep(0.5)`

**Comment by KevinLage** [comment]
do you even use python3?

**Comment by tora3268** [comment]
Thanks for the pointer. It seems working now.
