### ISSUE TITLE
help needed to write code for proxy source from text file and proxyscraper api

### ISSUE THREAD

**Issue by fthqrb** [KevinLage/YouTube-Livestream-Botter#65]
python noob here- how do i add 2 sources for proxy, one from proxyscraper api and another from desktop text file. thanks!

**Comment by KevinLage** [comment]
to read it from a file

proxy = open("proxy.txt", "r").readlines() or 
proxy = open("proxy.txt", "r").read() im not sure rn

**Comment by fthqrb** [comment]
thanks for the swift reply Kevin. 

good job on the bot btw. 

can i stack it with the proxyscraper url so it gets 2 sources of proxy?

**Comment by fthqrb** [comment]
![image](https://user-images.githubusercontent.com/64921354/81218737-41bd7300-9011-11ea-90bd-4afd4011a584.png)

is that correct? lol not sure if im doing it correctly

**Comment by fthqrb** [comment]
also, is it possible to get the number of botted views over 1k? i tried my proxies of thousands numbers still are on the 100s
