### ISSUE TITLE
anyone able to bot over 1k live viewers??

### ISSUE THREAD

**Issue by fthqrb** [KevinLage/YouTube-Livestream-Botter#66]
mine seems to be stuck at 100+- even with premium scrape proxies and additional urls.

anyone able to share workaround for this???

**Comment by KevinLage** [comment]
use private proxies (not public like proxyscrape)

**Comment by fthqrb** [comment]
i got a private proxy service of over 5k proxies and yet my views doesnt go past 200. it will trickle down after reaching 200. can u or anyone assist me in this and have a look at my code please? 

dett0#0524

**Comment by fthqrb** [comment]
any kind soul? heck i will pay to anyone that can successfully troubleshoot this issue for me to achieve >1k botted live views from my proxies

**Comment by AndreiCip** [comment]
> any kind soul? heck i will pay to anyone that can successfully troubleshoot this issue for me to achieve >1k botted live views from my proxies

Give me your discord/telegram
I could help you

**Comment by fthqrb** [comment]
> > any kind soul? heck i will pay to anyone that can successfully troubleshoot this issue for me to achieve >1k botted live views from my proxies
> 
> Give me your discord/telegram
> I could help you

thank you @AndreiCip 
my discord is dett0#0524

**Comment by tora3268** [comment]
> > any kind soul? heck i will pay to anyone that can successfully troubleshoot this issue for me to achieve >1k botted live views from my proxies
> 
> Give me your discord/telegram
> I could help you

what is your discord/telegram?

**Comment by tora3268** [comment]
> > any kind soul? heck i will pay to anyone that can successfully troubleshoot this issue for me to achieve >1k botted live views from my proxies
> 
> Give me your discord/telegram
> I could help you

@AndreiCip what is your discord/telegram?

**Comment by saqibrehan16** [comment]
i need 1k plus live view bottle plz help i will paid

**Comment by saqibrehan16** [comment]
@AndreiCip plz help me I need 1k plus YouTube live stream bot

**Comment by saqibrehan16** [comment]
You can help me 1k plus views
