### ISSUE TITLE
Stuck at 0

### ISSUE THREAD

**Issue by Forgotteninternet** [KevinLage/YouTube-Livestream-Botter#67]
It doesn't give any error message, and I'm able to connect to proxyscrape.com using my browser. I don't have any VPNs either. It just doesnt move from 0. I use 500-1000 threads, but I have also tried 100, 200, etc. Please help!

**Comment by fthqrb** [comment]
download version 1.3

**Comment by KevinLage** [comment]
yes download the latest version from releases
