### ISSUE TITLE
can't open file 'YouTube LivestreamBotter.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by IceBotYT** [KevinLage/YouTube-Livestream-Botter#69]
Help? Happens on execute from cmd

**Comment by 9ofe** [comment]
cd path/to/file
then python YouTube LivestreamBotter.py

**Comment by KevinLage** [comment]
use tab for autocomplete

**Comment by IceBotYT** [comment]
Sorry about that! Just had to go to releases! Just being an average person not knowing how to use GitHub. 😄

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
