### ISSUE TITLE
My bot isnt working

### ISSUE THREAD

**Issue by bangbang113** [KevinLage/YouTube-Livestream-Botter#72]
![Capture](https://user-images.githubusercontent.com/63899223/82611986-ca9ae980-9b8f-11ea-98ef-25fcfc483ba0.PNG)

**Comment by KevinLage** [comment]
something on your PC is blocking the request to proxyscrape.com

**Comment by bangbang113** [comment]
what thoughhh :(

**Comment by KevinLage** [comment]
idk what you have on your pc installed

**Comment by bangbang113** [comment]
do you have some type of screenshare?

**Comment by KevinLage** [comment]
no

**Comment by DasAlteUpdate** [comment]
I don't think there's anything blocking the motion. It seems more like an SSL error.    Maybe he has outdated SSL certificates?    Or his PC clock is not up2date. Or his Python installation does not work. (I don't think it is the last one).
