### ISSUE TITLE
 Stable online

### ISSUE THREAD

**Issue by Sovara** [KevinLage/YouTube-Livestream-Botter#76]
How to make threads turn off themselves? 30 minutes holds well. then there is a decline. restarting solves the problem. maybe something with closing threads is a problem?

**Comment by KevinLage** [comment]
afaik you cant stop only 1 thread the only thing you could do is restarting the whole script

**Comment by scramblr** [comment]
could maybe just assume a 30 minute refresh for now and sleep it until 1800

**Comment by KevinLage** [comment]
will maybe add something like this in the future
