### ISSUE TITLE
fix infinity +1 bot!

### ISSUE THREAD

**Issue by towuk118** [KevinLage/YouTube-Livestream-Botter#78]
https://github.com/KevinLage/YouTube-Livestream-Botter/blob/dd65a39b33a4d1888d5b0ac2c13604bd0019b3c9/YouTube%20Livestream%20Botter.py#L108

**Comment by KevinLage** [comment]
whats the problem?

**Comment by KevinLage** [comment]
as long as num is smaller then maxthreads (your input) it will create a new thread

**Comment by towuk118** [comment]
> as long as num is smaller then maxthreads (your input) it will create a new thread

i input "5" and bot chreate 5+ threads! check it!

**Comment by KevinLage** [comment]
can u send me a screenshot?

**Comment by towuk118** [comment]
okay one moment

> can u send me a screenshot?

ok one moment

**Comment by towuk118** [comment]
![image](https://user-images.githubusercontent.com/28830162/83516982-c3a19e80-a4e0-11ea-811e-e88dff8588ca.png)
![image](https://user-images.githubusercontent.com/28830162/83517015-d025f700-a4e0-11ea-87cc-b98d9a352bb0.png)

**Comment by KevinLage** [comment]
"botted" are not the threads it just shows how many requests were sent to the youtube api

**Comment by towuk118** [comment]
> "botted" are not the threads it just shows how many requests were sent to the youtube api

how use limit online counter?

**Comment by KevinLage** [comment]
what do you mean?

**Comment by towuk118** [comment]
> what do you mean?

example: i input 10 bot count and 10 online on stream

**Comment by KevinLage** [comment]
doesnt work
