### ISSUE TITLE
own proxy list please

### ISSUE THREAD

**Issue by sorusormak** [KevinLage/YouTube-Livestream-Botter#80]
own proxy list add your script please

**Comment by scramblr** [comment]
It's coming. In the meantime, change the proxy list to http://127.0.0.1:8000/my.proxies.txt and then run this command in the directory in which you have a file names my.proxies.txt:
cmdprompt$ python3 -m http.server 8000 --bind 127.0.0.1

**Comment by KevinLage** [comment]
added
