### ISSUE TITLE
The bots are decrease after 10~20 mintues.

### ISSUE THREAD

**Issue by s1725515** [KevinLage/YouTube-Livestream-Botter#86]
Sometimes increase and sometimes decrease.

**Comment by KevinLage** [comment]
just send me ur telegram name

**Comment by s1725515** [comment]
https://t.me/RudWan12

**Comment by s1725515** [comment]
> just send me ur telegram name

Can you contact me i'm waiting you..

**Comment by s1725515** [comment]
> https
