### ISSUE TITLE
Bots so slow.

### ISSUE THREAD

**Issue by ThomasZ3** [KevinLage/YouTube-Livestream-Botter#93]
Bots work but they're very slow.. i saw in some videos that it gets to 150 bots sent very quickly, while mine gets to 50 in like 30 minutes, do you know how to fix this?

**Comment by ThomasZ3** [comment]
So???

**Comment by KevinLage** [comment]
which specs does your PC have?

**Comment by KevinLage** [comment]
and how fast is your internet?

**Comment by ThomasZ3** [comment]
I have a 70 megabits download and 20 upload internet, and my pc has a gtx 1060 with an i3-8100 coffee lake, overall a medium pc and a pretty good internet so it shouldn't have problems

**Comment by ThomasZ3** [comment]
.

**Comment by KevinLage** [comment]
How much RAM do you have?
