### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by VARboosted** [KevinLage/YouTube-Livestream-Botter#96]
Hello I've tried couple softwares all of them not working, tried remove Python also not working and also removed antivirus.

![image](https://user-images.githubusercontent.com/37902495/84910994-42413300-b0c0-11ea-99e8-eb0afa43fc0f.png)

![image](https://user-images.githubusercontent.com/37902495/84910948-32295380-b0c0-11ea-8e0d-bb88e4b601fa.png)

**Comment by KevinLage** [comment]
yeah because the connection to proxyscrape is blocked 

can you access proxyscrape.com in your browser?

**Comment by VARboosted** [comment]
> proxyscrape.com

Shows me this:
![image](https://user-images.githubusercontent.com/37902495/85008704-ff399b00-b165-11ea-8e11-2bb4e7eecba3.png)

**Comment by KevinLage** [comment]
try to use a VPN

**Comment by VARboosted** [comment]
Can I do it without VPN, because I don't have,
the site works if i'm using browser vpn but i don't have a vpn software.

**Comment by KevinLage** [comment]
download the proxies from your browser and load them from a text file

**Comment by VARboosted** [comment]
How can I do it with the exe file?

**Comment by KevinLage** [comment]
download the latest version from releases

**Comment by VARboosted** [comment]
Downloaded..

**Comment by tranmaianh75** [comment]
Can I use YouTube-Livestream-Botter with WIN XP ???

**Comment by tranmaianh75** [comment]
KevinLage !! With WIN 7 YouTube-Livestream-Botter can run it ???

**Comment by tranmaianh75** [comment]
Hello !! KevinLage
With WIN 7 YouTube-Livestream-Botter can run it ??? because my PC not strong
