### ISSUE TITLE
bots dont work and shows and error screen pls help me 

### ISSUE THREAD

**Issue by Banzy101** [KevinLage/YouTube-Livestream-Botter#98]
![C__Users_nanab_OneDrive_Desktop_YouTube Livestream Botter exe 6_19_2020 12_41_52 AM](https://user-images.githubusercontent.com/67136507/85097531-c9c49a00-b1c5-11ea-86d0-32c557740daf.png)

**Comment by KevinLage** [comment]
can you access proxyscrape.com in your web browser?

**Comment by Banzy101** [comment]
never mind it wouldnt let me acess it because of my wifi now its good thank you!!!!!
